---
baseline: Death By Neon Music
theme:
- score
- artist
- music
keywords:
- artist page
- Death By Neon
author: starrylord.ch
date:
  format: j F Y
  timezone: Europe/Zürich
hyde:
  sidebar:
    sticky: true
  theme: ''
  reverse: false
title: Death By Neon
description: Artist DeathByNeon's music page
baseurl: https://deathbyneon.netlify.app
canonicalurl: true
