baseline: Death By Neon Music
theme:
  - hyde
  - hyde-cms
  - netlify
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Death By Neon
description: Artist DeathByNeon's music page
baseurl: https://deathbyneon.netlify.app
canonicalurl: true
